#!/bin/bash

echo "Testing Bomberman Lobby System"
echo "=============================="
echo ""
echo "This test will verify:"
echo "1. Player counter (2-4 players)"
echo "2. 20-second wait timer logic"
echo "3. 10-second countdown before game start"
echo ""
echo "Instructions:"
echo "1. Start the server: ./start-server.sh"
echo "2. Open multiple browser tabs to http://localhost:9090"
echo "3. Join multiplayer with different nicknames"
echo ""
echo "Expected behavior:"
echo "- With 1 player: Waiting for more players"
echo "- With 2 players: 20-second wait timer starts"
echo "- With 4 players: Immediate 10-second countdown"
echo "- Timer expires with 2+ players: 10-second countdown starts"
echo ""
echo "Test scenarios:"
echo ""
echo "Scenario 1: 2 players, wait for timer"
echo "- Join with 2 players"
echo "- Wait 20 seconds"
echo "- Should start 10-second countdown"
echo ""
echo "Scenario 2: 4 players, immediate countdown"
echo "- Join with 4 players quickly"
echo "- Should immediately start 10-second countdown"
echo ""
echo "Scenario 3: Player leaves during wait"
echo "- Join with 2 players"
echo "- One player leaves"
echo "- Timer should cancel"
echo ""
echo "Press any key to continue..."
read -n 1 -s
echo ""
echo "Starting server..."