export const GAME_CONFIG = {
    BLOCK_SIZE: 68,
    GRID_WIDTH: 15, // based on the map
    GRID_HEIGHT: 13,
    BOMB_TIMER: 3000,
    EXPLOSION_DURATION: 500,
    MAX_PLAYERS: 4,
    MIN_PLAYERS: 2,
    STARTING_LIVES: 3,
    BLOCK_DENSITY: 0.6,
    WAIT_TIMER: 2000, /////////////////////////
    COUNTDOWN_TIMER: 10000,
    POWERUP_SPAWN_CHANCE: 0.30
}
