export const ServerMessages = {
  // Connection
  CONNECTED: 'CONNECTED',
  ERROR: 'ERROR',
  PONG: 'PONG',
  // Lobby
  LOBBY_JOINED: 'LOBBY_JOINED',
  PLAYER_JOINED: 'PLAYER_JOINED',
  PLAYER_LEFT: 'PLAYER_LEFT',
  // Game Start
  COUNTDOWN_START: 'COUNTDOWN_START',
  COUNTDOWN_TICK: 'COUNTDOWN_TICK',
  GAME_STARTED: 'GAME_STARTED',
  // Game State
  FULL_STATE: 'FULL_STATE',
  // Game Events
  PLAYER_MOVED: 'PLAYER_MOVED',
  BOMB_PLACED: 'BOMB_PLACED',
  BOMB_EXPLODED: 'BOMB_EXPLODED',
  POWERUP_SPAWNED: 'POWERUP_SPAWNED',
  POWERUP_COLLECTED: 'POWERUP_COLLECTED',
  PLAYER_DAMAGED: 'PLAYER_DAMAGED',
  PLAYER_DIED: 'PLAYER_DIED',
  PLAYER_DISCONNECTED: 'PLAYER_DISCONNECTED',
  // Chat
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  // Game End
  GAME_OVER: 'GAME_OVER'
};

export const ClientMessages = {
  JOIN_GAME: 'JOIN_GAME',
  QUIT_GAME: 'QUIT_GAME',
  MOVE: 'MOVE',
  PLACE_BOMB: 'PLACE_BOMB',
  CHAT_MESSAGE: 'CHAT_MESSAGE'
}